mysql:
  enable: false
  ip: 127.0.0.1
  database: minecraft
  name: root
  password: 123456
  port: 3306

sign:
  default:
    day:
      - effect give {player} haste 600
      - give {player} diamond 1
    week:
      - effect give {player} strength 300 1
    twoweek:
      - effect give {player} strength 600 1
    threeweek:
      - effect give {player} strength 900 1
    month:
      - effect give {player} strength 1200 1
  vip:
    day:
      - effect give {player} haste 600 1
      - give {player} diamond 2
    week:
      - effect give {player} strength 300 1
    twoweek:
      - effect give {player} strength 600 1
    threeweek:
      - effect give {player} strength 900 1
    month:
      - effect give {player} strength 1200 1

draw:
  s:
    - '§d[大吉]闲适如春樱，清净如秋水。'
    - '§d[大吉]时光如轮转，时运今再来。'
    - '§d[大吉]人世清净，鬼界安宁，休矣。'
    - '§d[大吉]朦胧春月夜，美景世无双。'
    - '§d[大吉]四季交替，八方平安。'
  a:
    - '§b[中吉]满山枫似锦，祭神灵，运可转之。'
    - '§b[中吉]人间冥界均无事，难得一日可清闲。'
    - '§b[中吉]山中红叶犹可见，前程美景在暗中。'
    - '§b[中吉]人间渺渺栖百鬼，天地四处皆为家。'
    - '§b[中吉]邪灵恶鬼，终得严惩，不必担忧。'
    - '§b[中吉]是非难辨，凡事宜忍。'
    - '§b[中吉]诸行虽无常，自有潇洒意。'
    - '§b[中吉]从占卜之向，尊阴阳之道。'
  b:
    - '§a[小吉]世人皆俱魑魅物，鬼妖之中亦有情。'
    - '§a[小吉]鬼无心，神有眼，五行有道。'
    - '§a[小吉]天上悬明月，清辉照万方，浮云随暂避，终不灭清光。'
    - '§a[小吉]身愿随心，对明月，有圆缺。'
    - '§a[小吉]春樱虽随风飘散，仍有余香风转廊。'
    - '§a[小吉]人间黄泉路，切记有归途。'
    - '§a[小吉]八重樱花繁且枝盛，君须记累瓣必偿情。'
  c:
    - '§e[半吉]默念口中咒，所言非所思。'
    - '§e[半吉]吾身如浮萍，不敢言再会，幸得天眷顾，得挚友两三。'
    - '§e[半吉]应慎言，应慎行。'
    - '§e[半吉]天命如露滴，如幻更似虚，相逢若相知，逝去也足矣。'
    - '§e[半吉]胸中虽怀难言处，幸得有人问苦衷。'
    - '§e[半吉]沉浮尘世间，不必徒自添烦恼。'
    - '§e[半吉]鬼恶犹可治 人恶却难改。'
  d:
    - '[末吉]谨记鬼魅多生自人心。'
    - '[末吉]是非难辨，凡事宜忍。'
    - '[末吉]人间有人泣，鬼界有鬼哭。'
    - '[末吉]是生灭法，多加小心。'
    - '[末吉]莫与独鬼相语，所经之途必遭祸。'
    - '[末吉]莫仿飞蛾事，徒然扑夜灯，阴阳自有道，相顺不相违。'
    - '[末吉]鬼火之处，身似孤魂，前路何往。'